In [1]:
#Lista 10

#4) Ler a diagonal principal de uma matriz de 4x4 e preencher as células acima da diagonal com 1 e as
#abaixo com 2.

In [16]:
import numpy as np

In [30]:
A = np.random.randint(10,size=[4,4]) #matriz aleatória
print('Matriz A antes:\n',A)

for i in range(0,4):
    for j in range(0,4):
        if i > j:
            A[i,j] = 2
        elif i < j:
            A[i,j] = 1
print('\nMatriz A depois:\n',A,)

Matriz A antes:
 [[6 9 6 4]
 [1 4 9 2]
 [8 9 6 6]
 [2 8 9 6]]

Matriz A depois:
 [[6 1 1 1]
 [2 4 1 1]
 [2 2 6 1]
 [2 2 2 6]]
